app: PLACEHOLDER # should be overrided
ginMode: "debug"
httpPort: 80
grpcPort: 8000
promPort: 8080
ocAgentHost: ""
dbConfig:
  dsn: root:password@tcp(127.0.0.1:3306)/PLACEHOLDER?charset=utf8mb4&parseTime=True&loc=Local
  maxIdleConns: 3
  maxOpenConns: 10
localCacheConfig:
  expirationSeconds: 600
redisConfig:
  addrs: "127.0.0.1:7000"
  password: "pass.123"
  db: 0
  poolSize: 10
  maxRetries: 3
  expirationSeconds: 900
  idleTimeoutSeconds: 30
nats:
  clusterID: "test-cluster"
  url: "nats://127.0.0.1:4222"
  clientID: "" # will be randomly generated if not specified
  queueGroup: "orchestrator-queue"
  durableName: "purchase-svc-durable"
  subscriberCount: 3
rpcEndpoints:
  authSvcHost: ""
  productSvcHost: ""
serviceOptions:
  rps: 1000
  timeoutSecond: 10