// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package dep

import (
	"github.com/minghsu0107/saga-product/config"
	"github.com/minghsu0107/saga-product/infra"
	"github.com/minghsu0107/saga-product/infra/cache"
	"github.com/minghsu0107/saga-product/infra/db"
	"github.com/minghsu0107/saga-product/infra/grpc"
	"github.com/minghsu0107/saga-product/infra/http"
	pkg2 "github.com/minghsu0107/saga-product/infra/observe"
	"github.com/minghsu0107/saga-product/pkg"
	"github.com/minghsu0107/saga-product/repo"
	"github.com/minghsu0107/saga-product/repo/proxy"
	"github.com/minghsu0107/saga-product/service/product"
)

// Injectors from wire.go:

func InitializeServer() (*infra.Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	engine := http.NewEngine(configConfig)
	gormDB, err := db.NewDatabaseConnection(configConfig)
	if err != nil {
		return nil, err
	}
	idGenerator, err := pkg.NewSonyFlake()
	if err != nil {
		return nil, err
	}
	productRepository := repo.NewProductRepository(gormDB, idGenerator)
	localCache, err := cache.NewLocalCache(configConfig)
	if err != nil {
		return nil, err
	}
	clusterClient, err := cache.NewRedisClient(configConfig)
	if err != nil {
		return nil, err
	}
	redisCache := cache.NewRedisCache(configConfig, clusterClient)
	productRepoCache := proxy.NewProductRepoCache(configConfig, productRepository, localCache, redisCache)
	productService := product.NewProductService(configConfig, productRepoCache)
	sagaProductService := product.NewSagaProductService(configConfig, productRepoCache)
	router := http.NewRouter(productService, sagaProductService)
	server := http.NewServer(configConfig, engine, router)
	grpcServer := grpc.NewGRPCServer(configConfig, productService, sagaProductService)
	observibilityInjector, err := pkg2.NewObservibilityInjector(configConfig)
	if err != nil {
		return nil, err
	}
	infraServer := infra.NewServer(server, grpcServer, observibilityInjector)
	return infraServer, nil
}

func InitializeMigrator() (*db.Migrator, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	gormDB, err := db.NewDatabaseConnection(configConfig)
	if err != nil {
		return nil, err
	}
	migrator := db.NewMigrator(gormDB)
	return migrator, nil
}
